print('==========================')
m1 = int(input('Digite um número:'))
print(f'{m1} x 1 = {m1 * 1}')
print(f'{m1} x 2 = {m1 * 2}')
print(f'{m1} x 3 = {m1 * 3}')
print(f'{m1} x 4 = {m1 * 4}')
print(f'{m1} x 5 = {m1 * 5}')
print(f'{m1} x 6 = {m1 * 6}')
print(f'{m1} x 7 = {m1 * 7}')
print(f'{m1} x 8 = {m1 * 8}')
print(f'{m1} x 9 = {m1 * 9}')
print(f'{m1} x 10 = {m1 * 10}')
print(f'Essa é a tabuada de {m1}')
print('==========================')
